name: infra_did_comm_dart
description: Communication Protocol using Infra DID
version: 0.0.1
repository: https://github.com/InfraBlockchain/infra-did-comm-dart

environment:
  sdk: ">=3.0.1 <4.0.0"

dependencies:

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
