name: infra_did_comm_dart
description: Communication Protocol using Infra DID
version: 0.3.0
homepage:  https://github.com/InfraBlockchain/infra-did-comm-dart
repository: https://github.com/InfraBlockchain/infra-did-comm-dart

environment:
  sdk: ">=3.0.1 <4.0.0"

dependencies:
  uuid: ^3.0.6
  dart_jsonwebtoken: ^2.13.0
  convert: ^3.1.1
  jwk: ^0.2.3
  crypto_keys_plus: ^0.4.0
  meta: ^1.1.6
  typed_data: ^1.0.0
  x509_plus: ^0.3.1
  http: ">=0.13.0 <2.0.0"
  http_parser: ^4.0.0
  asn1lib: ^1.0.0
  collection: ^1.14.13
  clock: ^1.1.1
  substrate_bip39: ^0.4.0
  polkadart_keyring: ^0.4.3
  cryptography: ^2.7.0
  pinenacl: ^0.5.1
  socket_io_client: ^2.0.3+1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
